### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/compress-activity#1]

**Comment by Aniket21mathur** [comment]
@quozl there are already files named CompressCanvas3.py and utils3.py in GTK3 in this activity so these files can be renamed and the older utils.py and CompressCanvas.py can be deleted.Also there are some .pyo files that should be deleted and .gitignore should be accordingly updated.So should we proceed this way?
Thanks!

**Comment by quozl** [comment]
If that's what you think should be done, do it and make a pull request, thanks.  I don't want to check a plan when I will end up having to check a pull request as well.  I've no idea if both the GTK+ 2 and GTK+ 3 code have been maintained together.  That's rare.

**Comment by quozl** [comment]
Thanks for the pull request.  I understand better what you meant now.

This activity was already ported to GTK+ 3, should already be working with GTK+ 3, but happens to include GTK+ 2 compatibility in a way we've not seen before.  We did not plan for this.

So it looks like this issue was incorrectly created; and that's not surprising, since the method we gave to @yashagrawal3 included "does the activity reference GTK+ 2?".

Is there a reason to remove the GTK+ 2 support and leave only GTK+ 3 support present?

**Comment by rhl-bthr** [comment]
Interesting.
Are there systems running Sugar which don't support GTK+ 3 ?

**Comment by quozl** [comment]
Yes, there are systems where the imports of the GTK+ 3 won't complete without exception; because of earlier versions of Sugar still in use, or particularly early versions of GTK+ 3.  While I don't feel obliged to make sure that changes to the activity continue to work on GTK+ 2, actually removing this very well prepared compatibility without reason seems wrong.

By the way, this is another shallow repository extracted from a bundle, marked v14.  Another history can be found in http://git.sugarlabs.org/compress/compress which is currently at v16 and doesn't have GTK+ 3 support.  More careful comparison will be needed to figure out what this means.

**Comment by abhishektanwar** [comment]
@quozl @Aniket21mathur I want to port this activity to GTK+3 .I ran the activity and I am facing these errors 

If you could guide me a bit so that I can begin debugging this and obtain the desired result
```log
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 214, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/bin/sugar-activity", line 48, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/compress-activity.activity/Compress.py", line 42, in __init__
    canvas = PyApp()
  File "/usr/share/sugar/activities/compress-activity.activity/CompressCanvas3.py", line 504, in __init__
    if Gdk.Screen.width() >= 1200:
NameError: global name 'Gdk' is not defined
Exited with status 1, pid 1692 data (<open file '<fdopen>', mode 'w' at 0x7f0fd82a3ae0>, 'f5b6d864dcbea56c6345d8d0394716abe77d46e7')
```

**Comment by quozl** [comment]
You haven't imported Gdk.  Really, shouldn't ask us, this is a Python question, you're better off searching for the error or trying the same thing from the Python prompt.  It would be faster for me to port the activity myself (if I wanted it ported) rather than answer a row of similar questions.  :grin:

**Comment by Saumya-Mishra9129** [comment]
@quozl  Do this activity need both Gtk2 and Gtk3 support? I am thinking about working in this issue so I guess I have to make it compatible with both Gtk versions.

**Comment by quozl** [comment]
Source code for this activity is already compatible with both GTK versions.  It is a rare situation.  The method used to choose which version to use is rather blunt, but could work.  I think the question could be phrased as "do we need GTK 2 support?".  I don't think we do, but I don't see why we should remove it if the GTK 2 support can be maintained.  Someone wanted it this way once, and they may have had a reason.  Another question, which we always face, is "do we need this activity?".  There's also the other git repository to be considered.
